# docker-compose.yml
version: "3"
services:
  database:
    image: "postgres"
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=postgres
    ports:
      - "5532:5432"
